plugins {
	id 'java-library'
	id 'net.neoforged.moddev' version '2.0.141'
	id 'maven-publish'
	id 'io.freefair.lombok' version '8.6'
}

version = project.mod_version + "_" + project.minecraft_version
group = project.mod_group_id

base {
	archivesName = project.archives_base_name
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

repositories {
	mavenCentral()
}

neoForge {
	version = project.neo_version

	runs {
		client {
			client()
		}
		server {
			server()
		}
	}

	mods {
		"${project.mod_id}" {
			sourceSet sourceSets.main
		}
	}
}

dependencies {
}

processResources {
	def replaceProperties = [
		minecraft_version      : minecraft_version,
		minecraft_version_range: minecraft_version_range,
		neo_version            : neo_version,
		neo_version_range      : neo_version_range,
		loader_version_range   : loader_version_range,
		mod_id                 : mod_id,
		mod_version            : mod_version,
		mod_group_id           : mod_group_id,
	]
	inputs.properties replaceProperties

	filesMatching(['META-INF/neoforge.mods.toml']) {
		expand replaceProperties + [project: project]
	}
}

test {
	useJUnitPlatform()
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.base.archivesName.get()}" }
	}
}

// configure the maven publication
publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}
